name: inuachama
description: A new Flutter project.
flutter_native_splash:
  image: assets/images/splash.png
  color: "#FFFFFF"
  fill: false
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
publish_to: 'none'
version: 1.0.0+6
environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.7
  http: ^0.13.3
  intl: ^0.17.0
  path_provider: ^2.0.11
  image_picker: ^0.8.4+2
  cached_network_image: ^3.2.2
  dio: ^4.0.0
  toggle_switch: ^2.0.1
  permission_handler: ^9.2.0
  overlay_support: ^2.0.1
  flutter_launcher_icons: ^0.9.2
  numberpicker: ^2.1.1
  flutter_typeahead: ^4.0.0
  open_file: ^3.2.1
  responsive_framework: ^0.2.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.8
  change_app_package_name: ^1.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: NunitoSans-Regular
      fonts:
        - asset: font/NunitoSans-Regular.ttf
  
  
  
  
  
